[package]
name = "day1"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "*", features = ["blocking"] }
dotenv = "*"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "criterion"
harness = false
